// <auto-generated />
using DependecyInjection2.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DependecyInjection2.Migrations
{
    [DbContext(typeof(CountryDbContext))]
    [Migration("20240624191709_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DependecyInjection2.Domain.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Nombre = "Argentina"
                        },
                        new
                        {
                            Id = "2",
                            Nombre = "Francia"
                        },
                        new
                        {
                            Id = "3",
                            Nombre = "Brasil"
                        },
                        new
                        {
                            Id = "4",
                            Nombre = "Chile"
                        },
                        new
                        {
                            Id = "5",
                            Nombre = "Paraguay"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
